### ISSUE TITLE
Invalid bundle ID for container error

### ISSUE THREAD

**Issue by slenderman2511** [apple/cloudkit-sample-queries#1]
![Simulator Screen Shot - iPhone 13 - 2022-04-13 at 14 07 15](https://user-images.githubusercontent.com/91517301/163119653-806de3d0-7ab6-45e1-81a3-08d7982d9b61.png)
I got this problem when try out. Can you give me a solution to fix this?

**Comment by sjrmanning** [comment]
Hi! This looks like the application bundle ID might not be associated with your CloudKit container. You can check in Xcode under "Signing & Capabilities" to ensure it's configured correctly, and [this document](https://developer.apple.com/documentation/cloudkit/enabling_cloudkit_in_your_app) has some more details on what's involved.

**Comment by sjrmanning** [comment]
Please feel free to re-open this issue if you have troubled following the above steps.

**Comment by cs-moushuai** [comment]
Regarding this issue, first, you need to make sure that the `containerIdentifier` in Config.swift is correct. 

Additionally, it's important to note that I found that regardless of whether modifyRecordZones is successful or not, `UserDefaults.standard.set(true, forKey: "contactZoneCreated")` will be executed in the following code:

```swift
    /// Creates a custom CKRecordZone and saves it to the database if needed,
    /// checking `UserDefaults` if this has been done before on this device.
    private func createContactsZoneIfNeeded() async throws {
        guard !UserDefaults.standard.bool(forKey: "contactZoneCreated") else {
            return
        }

        let newZone = CKRecordZone(zoneID: contactsZoneID)
        _ = try await database.modifyRecordZones(saving: [newZone], deleting: [])

        UserDefaults.standard.set(true, forKey: "contactZoneCreated")
    }
```
This means that even if you correct the error in Config.swift later, you still won't be able to create a zone.

The viable solution is to manually create the zone in CloudKit Dashboard or use `UserDefaults.standard.set(false, forKey: "contactZoneCreated")` in your code to enable `modifyRecordZones` to run again.
